services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      REDIS: "redis:6379"